In [1]:
root = 'D:\Data\My_MMFi_Data\MMFi_Dataset'
import os
for env in sorted(os.listdir(root)):
    print(env)
    for subject in sorted(os.listdir(os.path.join(root, env))):
        print(subject)
        for activity in sorted(os.listdir(os.path.join(root, env, subject))):
            # print(activity)
            # print(os.path.join(root, env, subject, activity))
            for modality in ['rgb','depth','lidar','wifi-csi']:
                # print(modality)
                num = len(os.listdir(os.path.join(root, env, subject, activity, modality)))
                if num == 297:
                    continue
                else:
                    print(env, subject, activity, modality, num)
            #     break
            # break
    #     break
    # break


E01
S01
S02
S03
S04
S05
S06
S07
S08
S09
S10
E02
S11
S12
S13
S14
S15
S16
S17
S18
S19
S20
E03
S21
S22
S23
S24
S25
S26
S27
S28
S29
S30
E04
S31
S32
S33
S34
S35
S36
S37
S38
S39
S40


In [2]:
import torch
import torch.nn as nn

In [ ]:
class linear_projector(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(linear_projector, self).__init__()
        self.linear_projection = nn.Conv1d(input_dim, output_dim, 1, 1, 0)
    # def forward(self, rgb_feature, depth_feature, mmwave_feature, lidar_feature, csi_feature, modality_list):
    #     feature_list = [rgb_feature, depth_feature, mmwave_feature, lidar_feature, csi_feature]
    #     if sum (modality_list) == 0:
    #         print('WARNING: modality_list is empty!')
    #         feature = torch.zeros_like(lidar_feature, device=torch.device('cuda'))
    #         feature = self.linear_projection(feature)
    #     else:
    #         real_feature_list = []
    #         for i in range(len(modality_list)):
    #             if modality_list[i] == True:
    #                 real_feature_list.append(feature_list[i])
    #             else:
    #                 continue
    #         feature = torch.cat(real_feature_list, dim=1)
    #         feature = self.linear_projection(feature)
    #     return feature
    def forward(self, rgb_feature, depth_feature, mmwave_feature, lidar_feature, csi_feature, modality_list):
        feature_list = [rgb_feature, depth_feature, mmwave_feature, lidar_feature, csi_feature]

In [9]:
features = [torch.randn(16,32,512), torch.randn(16,32,512), torch.randn(16,32,512)]
for i in range(len(features)):
    print(features[i][:,0,0])
feature_embedding = torch.zeros(features[0].shape).to(features[0].device)
# print(feature_embedding)
for single_feature in features:
    feature_embedding = torch.add(feature_embedding, single_feature, alpha=1)
    print(feature_embedding[:,0,0])
# print(feature_embedding.shape)
feature_embedding = torch.div(feature_embedding, 3)
print(feature_embedding[:,0,0])

tensor([ 1.0738, -2.0590, -0.4823, -0.7991, -0.5433,  0.2063,  2.6042, -0.7325,
         0.1970,  1.3581,  0.0157, -0.1309, -1.9995,  0.5261,  1.2761, -0.5081])
tensor([ 1.7910,  0.1227,  0.4035,  0.6901,  0.1704, -0.2732,  0.0046, -0.9625,
        -1.3507, -0.8886, -0.7415,  0.1576,  0.2561, -1.8297,  0.2314, -0.9118])
tensor([ 0.0409,  1.3215, -0.9362,  0.0041,  0.4278, -0.1733,  0.6391, -0.6053,
         0.7920, -0.2561,  0.2725, -1.0825, -0.2974, -0.3699, -1.1774, -0.2120])
tensor([ 1.0738, -2.0590, -0.4823, -0.7991, -0.5433,  0.2063,  2.6042, -0.7325,
         0.1970,  1.3581,  0.0157, -0.1309, -1.9995,  0.5261,  1.2761, -0.5081])
tensor([ 2.8649, -1.9362, -0.0788, -0.1089, -0.3729, -0.0669,  2.6088, -1.6951,
        -1.1537,  0.4695, -0.7257,  0.0266, -1.7434, -1.3037,  1.5075, -1.4199])
tensor([ 2.9058, -0.6147, -1.0150, -0.1048,  0.0549, -0.2402,  3.2480, -2.3004,
        -0.3617,  0.2134, -0.4532, -1.0559, -2.0409, -1.6735,  0.3301, -1.6319])
tensor([ 0.9686, -0.2049, -0.3383,

In [7]:
import random

def generate_none_empth_modality_list():
    modality_list = random.choices(
        [True, False],
        k= 5,
        weights=[1, 99]
    )
    print(modality_list)
    if sum(modality_list) == 0:
        modality_list = generate_none_empth_modality_list()
        return modality_list
    else:
        return modality_list

modality_list = generate_none_empth_modality_list()
print(modality_list)

[False, False, False, False, False]
[False, False, False, False, False]
[False, False, False, False, False]
[False, False, False, False, False]
[False, False, False, False, False]
[False, False, False, False, False]
[False, False, False, False, False]
[False, False, False, False, False]
[False, False, False, False, False]
[False, False, False, False, False]
[False, True, False, False, False]
[False, True, False, False, False]


In [1]:
'model with pos encoding'
import torch
import sys
from MI_model_5 import modality_invariant_model

model = modality_invariant_model()
model.cuda()

rgb_data = torch.randn(16, 3, 480, 640).cuda()
depth_data = torch.randn(16, 3, 480, 640).cuda()
lidar_data = torch.randn(16, 1432, 3).cuda()
mmwave_data = torch.randn(16, 67, 5).cuda()
wifi_data = torch.randn(16, 3, 114, 10).cuda()
modality_list = [False, True, False, True, False]
# modality_list = [True, True, True, True, True]
# modality_list = [False, False, False, False, False]

out = model(rgb_data, depth_data,  mmwave_data, lidar_data, wifi_data, modality_list)

print(out.shape)
# print(model)

torch.Size([16, 17, 3])
